---
title: Rick's Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
brief-intro: QA Engineer for cloud storage now
baseurl: 
url: https://blog.zgx.io
permalink: "/:year/:month/:day/:title/"
twitter_username: 
facebook_username: 
github_username: rickzhen
email: me@zgx.io
weibo_username: 
zhihu_username: zgxme
douban_username: zgxme
linkedIn_username: 
dribbble_username: 
description_footer: 这里记录我的所学所得！
duoshuo_shortname: 
disqus_shortname: zgx
baidu_tongji_id: afce4fbd8441721cccfbe5650f07887b
google_analytics_id: 
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
category_dir: category/
tag_dir: tag/
excerpt_separator: |2+




gems:
- jekyll-paginate
paginate: 10
plugins:
- jekyll-paginate
